! DISTRIBUTION STATEMENT A. Approved for public release; distribution is
! unlimited.  Granted clearance per 88ABW-YYYY-ZZZZ.
!
! This file is declared a work of the U.S. Government and is not subject to
! copyright protection in the United States.

PROGRAM COMBINED_1

  USE XDR
  USE ASSERT
  USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_CHAR, C_DOUBLE, C_INT32_T, C_SIZE_T
  IMPLICIT NONE

  LOGICAL :: CODE
  TYPE(XDR_T) :: XDRS
  INTEGER(KIND = C_SIZE_T) :: LENGTH
  LOGICAL, DIMENSION(2) :: ACTUAL_LOGICAL
  LOGICAL, DIMENSION(2) :: EXPECTED_LOGICAL
  INTEGER(KIND = C_INT32_T), DIMENSION(3) :: ACTUAL_INTEGER
  INTEGER(KIND = C_INT32_T), DIMENSION(3) :: EXPECTED_INTEGER
  REAL(KIND = C_DOUBLE), DIMENSION(6) :: ACTUAL_REAL
  REAL(KIND = C_DOUBLE), DIMENSION(6) :: EXPECTED_REAL
  CHARACTER(KIND = C_CHAR, LEN = 16), DIMENSION(3) :: ACTUAL_STRING
  CHARACTER(KIND = C_CHAR, LEN = 16), DIMENSION(3) :: EXPECTED_STRING

  CALL XDRS%CREATE(140)

  EXPECTED_LOGICAL(1) = .TRUE.
  EXPECTED_LOGICAL(2) = .FALSE.
  CODE = XDRS%PUT_VECTOR(EXPECTED_LOGICAL, 2_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  EXPECTED_INTEGER(1) = 123
  EXPECTED_INTEGER(2) = 456
  EXPECTED_INTEGER(3) = 789
  CODE = XDRS%PUT_ARRAY(EXPECTED_INTEGER, 10_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  EXPECTED_REAL(1) = 1.23
  EXPECTED_REAL(2) = 4.56
  EXPECTED_REAL(3) = 7.89
  EXPECTED_REAL(4) = -1.23
  EXPECTED_REAL(5) = -4.56
  EXPECTED_REAL(6) = -7.89
  CODE = XDRS%PUT_ARRAY(EXPECTED_REAL, 10_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  EXPECTED_STRING(1) = 'Hello'
  EXPECTED_STRING(2) = 'Bonjour'
  EXPECTED_STRING(3) = 'Konnichi wa'
  CODE = XDRS%PUT_ARRAY(EXPECTED_STRING, 10_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%SETPOS(1_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  ACTUAL_LOGICAL = .FALSE.
  CODE = XDRS%GET_VECTOR(ACTUAL_LOGICAL, 2_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_TRUE(ACTUAL_LOGICAL(1) .EQV. EXPECTED_LOGICAL(1))
  CALL ASSERT_TRUE(ACTUAL_LOGICAL(2) .EQV. EXPECTED_LOGICAL(2))

  ACTUAL_INTEGER = 0
  CODE = XDRS%GET_ARRAY(ACTUAL_INTEGER, LENGTH)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_EQUALS(SIZE(EXPECTED_INTEGER), INT(LENGTH))
  CALL ASSERT_ARRAY_EQUALS(EXPECTED_INTEGER, ACTUAL_INTEGER)

  ACTUAL_REAL = 0_C_DOUBLE
  CODE = XDRS%GET_ARRAY(ACTUAL_REAL, LENGTH)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_EQUALS(SIZE(EXPECTED_REAL), INT(LENGTH))
  CALL ASSERT_ARRAY_EQUALS(EXPECTED_REAL, ACTUAL_REAL, 1.0E-16_C_DOUBLE)

  ACTUAL_STRING = ''
  CODE = XDRS%GET_ARRAY(ACTUAL_STRING, LENGTH)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_EQUALS(SIZE(EXPECTED_STRING), INT(LENGTH))
  CALL ASSERT_TRUE(EXPECTED_STRING(1) == ACTUAL_STRING(1))
  CALL ASSERT_TRUE(EXPECTED_STRING(2) == ACTUAL_STRING(2))
  CALL ASSERT_TRUE(EXPECTED_STRING(3) == ACTUAL_STRING(3))

  CALL XDRS%DESTROY()

END PROGRAM
