! DISTRIBUTION STATEMENT A. Approved for public release; distribution is
! unlimited.  Granted clearance per 88ABW-YYYY-ZZZZ.
!
! This file is declared a work of the U.S. Government and is not subject to
! copyright protection in the United States.

PROGRAM GET_ARRAY_DOUBLE

  USE XDR
  USE ASSERT
  USE HELPERS
  USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_DOUBLE, C_SIZE_T
  IMPLICIT NONE

  TYPE(XDR_T) :: XDRS
  CHARACTER(LEN = 256) :: FILENAME
  REAL(KIND = C_DOUBLE), DIMENSION(3) :: VALUES
  INTEGER(KIND = C_SIZE_T) :: LENGTH
  LOGICAL :: CODE

  CALL FILE_PATH('array_double.xdr', FILENAME)
  CALL XDRS%READ_FILE(FILENAME)

  CODE = XDRS%GET_ARRAY(VALUES, LENGTH)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_EQUALS(3, INT(LENGTH))
  CALL ASSERT_EQUALS( 1.23456E+300_C_DOUBLE, VALUES(1), 1.0E-306_C_DOUBLE)
  CALL ASSERT_EQUALS(-2.34567E+300_C_DOUBLE, VALUES(2), 1.0E-306_C_DOUBLE)
  CALL ASSERT_EQUALS( 3.45678E-300_C_DOUBLE, VALUES(3), 1.0E-306_C_DOUBLE)

  CALL XDRS%DESTROY()

END PROGRAM
