PROGRAM GET_DOUBLE

  USE XDR
  USE ASSERT
  USE HELPERS
  USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_DOUBLE
  IMPLICIT NONE

  TYPE(XDR_T) :: XDRS
  CHARACTER(LEN = 256) :: FILENAME
  REAL(KIND = C_DOUBLE) :: VALUE
  LOGICAL :: CODE

  CALL FILE_PATH('sample_double.xdr', FILENAME)
  CALL XDRS%READ_FILE(FILENAME)

  CODE = XDRS%GET(VALUE)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_EQUALS( 1.23456E+300_C_DOUBLE, VALUE, 1.0E-306_C_DOUBLE)

  CODE = XDRS%GET(VALUE)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_EQUALS(-2.34567E+300_C_DOUBLE, VALUE, 1.0E-306_C_DOUBLE)

  CODE = XDRS%GET(VALUE)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_EQUALS( 3.45678E-300_C_DOUBLE, VALUE, 1.0E-306_C_DOUBLE)

  CODE = XDRS%GET(VALUE)
  CALL ASSERT_FALSE(CODE)

  CALL XDRS%DESTROY()

END PROGRAM
