! DISTRIBUTION STATEMENT A. Approved for public release; distribution is
! unlimited.  Granted clearance per 88ABW-YYYY-ZZZZ.
!
! This file is declared a work of the U.S. Government and is not subject to
! copyright protection in the United States.

PROGRAM GET_CHAR

  USE XDR
  USE ASSERT
  USE HELPERS
  USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_CHAR
  IMPLICIT NONE

  TYPE(XDR_T) :: XDRS
  CHARACTER(LEN = 256) :: FILENAME
  CHARACTER(KIND = C_CHAR) :: VALUE
  LOGICAL :: CODE

  CALL FILE_PATH('sample_char.xdr', FILENAME)
  CALL XDRS%READ_FILE(FILENAME)

  CODE = XDRS%GET_CHARACTER(VALUE)
  CALL ASSERT_TRUE('a' == VALUE)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%GET_CHARACTER(VALUE)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_TRUE('b' == VALUE)

  CODE = XDRS%GET_CHARACTER(VALUE)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_TRUE('c' == VALUE)

  CODE = XDRS%GET_CHARACTER(VALUE)
  CALL ASSERT_FALSE(CODE)

  CALL XDRS%DESTROY()

END PROGRAM
