PROGRAM GET_VECTOR_LOGICAL

  USE XDR
  USE ASSERT
  USE HELPERS
  USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_SIZE_T
  IMPLICIT NONE

  TYPE(XDR_T) :: XDRS
  CHARACTER(LEN = 256) :: FILENAME
  LOGICAL, DIMENSION(2) :: VALUES
  LOGICAL :: CODE

  CALL FILE_PATH('sample_bool.xdr', FILENAME)
  CALL XDRS%READ_FILE(FILENAME)

  CODE = XDRS%GET_VECTOR(VALUES, 2_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_FALSE(VALUES(1))
  CALL ASSERT_TRUE(VALUES(2))

  CALL XDRS%DESTROY()

END PROGRAM
