PROGRAM PUT_DOUBLE

  USE XDR
  USE ASSERT
  USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_DOUBLE, C_SIZE_T
  IMPLICIT NONE

  TYPE(XDR_T) :: XDRS
  REAL(KIND = C_DOUBLE) :: VALUE
  LOGICAL :: CODE

  CALL XDRS%CREATE(24)

  CODE = XDRS%PUT( 1.23456E+300_C_DOUBLE)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%PUT(-2.34567E+300_C_DOUBLE)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%PUT( 3.45678E-300_C_DOUBLE)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%PUT( 3.45678E-300_C_DOUBLE)
  CALL ASSERT_FALSE(CODE)

  CODE = XDRS%SETPOS(1_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%GET(VALUE)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_EQUALS( 1.23456E+300_C_DOUBLE, VALUE, 1.0E-306_C_DOUBLE)

  CODE = XDRS%GET(VALUE)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_EQUALS(-2.34567E+300_C_DOUBLE, VALUE, 1.0E-306_C_DOUBLE)

  CODE = XDRS%GET(VALUE)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_EQUALS( 3.45678E-300_C_DOUBLE, VALUE, 1.0E-306_C_DOUBLE)

  CODE = XDRS%GET(VALUE)
  CALL ASSERT_FALSE(CODE)

  CALL XDRS%DESTROY()

END PROGRAM
