PROGRAM PUT_ARRAY_LOGICAL

  USE XDR
  USE ASSERT
  USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_SIZE_T
  IMPLICIT NONE

  TYPE(XDR_T) :: XDRS
  LOGICAL, DIMENSION(2) :: VALUES
  LOGICAL, DIMENSION(:), ALLOCATABLE :: OUTPUTS
  LOGICAL :: CODE

  CALL XDRS%CREATE(12)

  VALUES(1) = .FALSE.
  VALUES(2) = .TRUE.
  CODE = XDRS%PUT_ARRAY(VALUES, 2_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%SETPOS(1_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%GET_ARRAY(OUTPUTS, 2_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_FALSE(OUTPUTS(1))
  CALL ASSERT_TRUE(OUTPUTS(2))
  DEALLOCATE(OUTPUTS)

  CALL XDRS%DESTROY()

END PROGRAM
