PROGRAM PUT_VECTOR_UINT8_T

  USE XDR
  USE ASSERT
  USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT16_T, C_SIZE_T
  IMPLICIT NONE

  TYPE(XDR_T) :: XDRS
  INTEGER(KIND = C_INT16_T), DIMENSION(3) :: VALUES
  LOGICAL :: CODE

  CALL XDRS%CREATE(12)

  VALUES(1) =   0
  VALUES(2) = 127
  VALUES(3) = 255
  CODE = XDRS%PUT_UNSIGNED_VECTOR(VALUES, 3_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  VALUES = 0_C_INT16_T
  CODE = XDRS%SETPOS(1_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%GET_UNSIGNED_VECTOR(VALUES, 3_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_EQUALS(  0, INT(VALUES(1)))
  CALL ASSERT_EQUALS(127, INT(VALUES(2)))
  CALL ASSERT_EQUALS(255, INT(VALUES(3)))

  CALL XDRS%DESTROY()

END PROGRAM
