! DISTRIBUTION STATEMENT A. Approved for public release; distribution is
! unlimited.  Granted clearance per 88ABW-2016-0371.
!
! This file is declared a work of the U.S. Government and is not subject to
! copyright protection in the United States.

PROGRAM PUT_FLOAT

  USE XDR
  USE ASSERT
  USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_FLOAT, C_SIZE_T
  IMPLICIT NONE

  TYPE(XDR_T) :: XDRS
  REAL(KIND = C_FLOAT) :: VALUE
  LOGICAL :: CODE

  CALL XDRS%CREATE(12)

  CODE = XDRS%PUT( 1.23456E+30_C_FLOAT)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%PUT(-2.34567E+30_C_FLOAT)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%PUT( 3.45678E-30_C_FLOAT)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%PUT( 3.45678E-30_C_FLOAT)
  CALL ASSERT_FALSE(CODE)

  CODE = XDRS%SETPOS(1_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%GET(VALUE)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_EQUALS( 1.23456E+30_C_FLOAT, VALUE, 1.0E-36_C_FLOAT)

  CODE = XDRS%GET(VALUE)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_EQUALS(-2.34567E+30_C_FLOAT, VALUE, 1.0E-36_C_FLOAT)

  CODE = XDRS%GET(VALUE)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_EQUALS( 3.45678E-30_C_FLOAT, VALUE, 1.0E-36_C_FLOAT)

  CODE = XDRS%GET(VALUE)
  CALL ASSERT_FALSE(CODE)

  CALL XDRS%DESTROY()

END PROGRAM
