PROGRAM PUT_ARRAY_FLOAT

  USE XDR
  USE ASSERT
  USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_FLOAT, C_SIZE_T
  IMPLICIT NONE

  TYPE(XDR_T) :: XDRS
  REAL(KIND = C_FLOAT), DIMENSION(3) :: VALUES
  REAL(KIND = C_FLOAT), DIMENSION(:), ALLOCATABLE :: OUTPUTS
  LOGICAL :: CODE

  CALL XDRS%CREATE(16)

  VALUES(1) =  1.23456E+30_C_FLOAT
  VALUES(2) = -2.34567E+30_C_FLOAT
  VALUES(3) =  3.45678E-30_C_FLOAT
  CODE = XDRS%PUT_ARRAY(VALUES, 3_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%SETPOS(1_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%ALLOCATE_ARRAY(OUTPUTS, 3_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_EQUALS( 1.23456E+30_C_FLOAT, OUTPUTS(1), 1.0E-36_C_FLOAT)
  CALL ASSERT_EQUALS(-2.34567E+30_C_FLOAT, OUTPUTS(2), 1.0E-36_C_FLOAT)
  CALL ASSERT_EQUALS( 3.45678E-30_C_FLOAT, OUTPUTS(3), 1.0E-36_C_FLOAT)
  DEALLOCATE(OUTPUTS)

  CALL XDRS%DESTROY()

END PROGRAM
