PROGRAM PUT_ARRAY_STRING

  USE XDR
  USE ASSERT
  USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_CHAR, C_SIZE_T
  IMPLICIT NONE

  TYPE(XDR_T) :: XDRS
  CHARACTER(KIND = C_CHAR, LEN = 6), DIMENSION(3) :: VALUES
  CHARACTER(KIND = C_CHAR, LEN = 6), DIMENSION(:), ALLOCATABLE :: OUTPUTS
  LOGICAL :: CODE

  CALL XDRS%CREATE(40)

  VALUES(1) = 'abcdef'
  VALUES(2) = 'ghijkl'
  VALUES(3) = 'mnopqr'
  CODE = XDRS%PUT_ARRAY(VALUES, 3_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%SETPOS(1_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%GET_ARRAY(OUTPUTS, 3_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_TRUE('abcdef' == OUTPUTS(1))
  CALL ASSERT_TRUE('ghijkl' == OUTPUTS(2))
  CALL ASSERT_TRUE('mnopqr' == OUTPUTS(3))
  DEALLOCATE(OUTPUTS)

  CALL XDRS%DESTROY()

END PROGRAM
