PROGRAM PUT_VECTOR_BYTES

  USE XDR
  USE ASSERT
  USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_CHAR, C_SIZE_T
  IMPLICIT NONE

  TYPE(XDR_T) :: XDRS
  CHARACTER(KIND = C_CHAR, LEN = 6), DIMENSION(3) :: VALUES
  INTEGER(KIND = C_SIZE_T), DIMENSION(3) :: LENGTHS
  LOGICAL :: CODE

  CALL XDRS%CREATE(36)

  VALUES(1) = 'abcdef'
  VALUES(2) = 'ghijkl'
  VALUES(3) = 'mnopqr'
  LENGTHS(1) = 6
  LENGTHS(2) = 6
  LENGTHS(3) = 6
  CODE = XDRS%PUT_VECTOR(VALUES, LENGTHS, 3_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  VALUES = '---'
  LENGTHS = 0
  CODE = XDRS%SETPOS(1_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%GET_VECTOR(VALUES, LENGTHS, 3_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_EQUALS(6, INT(LENGTHS(1)))
  CALL ASSERT_EQUALS(6, INT(LENGTHS(2)))
  CALL ASSERT_EQUALS(6, INT(LENGTHS(3)))
  CALL ASSERT_TRUE('abcdef' == VALUES(1))
  CALL ASSERT_TRUE('ghijkl' == VALUES(2))
  CALL ASSERT_TRUE('mnopqr' == VALUES(3))

  CALL XDRS%DESTROY()

END PROGRAM
