PROGRAM PUT_ARRAY_BYTES

  USE XDR
  USE ASSERT
  USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_CHAR, C_SIZE_T
  IMPLICIT NONE

  TYPE(XDR_T) :: XDRS
  CHARACTER(KIND = C_CHAR, LEN = 6), DIMENSION(3) :: VALUES
  CHARACTER(KIND = C_CHAR, LEN = 6), DIMENSION(:), ALLOCATABLE :: OUTPUTS
  INTEGER(KIND = C_SIZE_T), DIMENSION(3) :: LENGTHS
  INTEGER(KIND = C_SIZE_T), DIMENSION(:), ALLOCATABLE :: SIZES
  LOGICAL :: CODE

  CALL XDRS%CREATE(40)

  VALUES(1) = 'abcdef'
  VALUES(2) = 'ghijkl'
  VALUES(3) = 'mnopqr'
  LENGTHS(1) = 6
  LENGTHS(2) = 6
  LENGTHS(3) = 6
  CODE = XDRS%PUT_ARRAY(VALUES, LENGTHS, 3_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%SETPOS(1_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%GET_ARRAY(OUTPUTS, SIZES, 3_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_EQUALS(6, INT(SIZES(1)))
  CALL ASSERT_EQUALS(6, INT(SIZES(2)))
  CALL ASSERT_EQUALS(6, INT(SIZES(3)))
  CALL ASSERT_TRUE('abcdef' == OUTPUTS(1))
  CALL ASSERT_TRUE('ghijkl' == OUTPUTS(2))
  CALL ASSERT_TRUE('mnopqr' == OUTPUTS(3))
  DEALLOCATE(OUTPUTS)
  DEALLOCATE(SIZES)

  CALL XDRS%DESTROY()

END PROGRAM
