PROGRAM PUT_UINT32_T

  USE XDR
  USE ASSERT
  USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT64_T, C_SIZE_T
  IMPLICIT NONE

  TYPE(XDR_T) :: XDRS
  INTEGER(KIND = C_INT64_T) :: VALUE
  LOGICAL :: CODE

  CALL XDRS%CREATE(12)

  CODE = XDRS%PUT_UNSIGNED(0_C_INT64_T)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%PUT_UNSIGNED(2147483648_C_INT64_T)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%PUT_UNSIGNED(4294967295_C_INT64_T)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%PUT_UNSIGNED(4294967295_C_INT64_T)
  CALL ASSERT_FALSE(CODE)

  CODE = XDRS%SETPOS(1_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%GET_UNSIGNED(VALUE)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_EQUALS(0_C_INT64_T, VALUE)

  CODE = XDRS%GET_UNSIGNED(VALUE)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_EQUALS(2147483648_C_INT64_T, VALUE)

  CODE = XDRS%GET_UNSIGNED(VALUE)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_EQUALS(4294967295_C_INT64_T, VALUE)

  CODE = XDRS%GET(VALUE)
  CALL ASSERT_FALSE(CODE)

  CALL XDRS%DESTROY()

END PROGRAM
