PROGRAM PUT_ARRAY_CHAR

  USE XDR
  USE ASSERT
  USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_CHAR, C_SIZE_T
  IMPLICIT NONE

  TYPE(XDR_T) :: XDRS
  CHARACTER(KIND = C_CHAR), DIMENSION(3) :: VALUES
  CHARACTER(KIND = C_CHAR), DIMENSION(:), ALLOCATABLE :: OUTPUTS
  LOGICAL :: CODE

  CALL XDRS%CREATE(16)

  VALUES(1) = 'a'
  VALUES(2) = 'b'
  VALUES(3) = 'c'
  CODE = XDRS%PUT_CHARACTER_ARRAY(VALUES, 3_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%SETPOS(1_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%GET_CHARACTER_ARRAY(OUTPUTS, 3_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_TRUE('a' == OUTPUTS(1))
  CALL ASSERT_TRUE('b' == OUTPUTS(2))
  CALL ASSERT_TRUE('c' == OUTPUTS(3))
  DEALLOCATE(OUTPUTS)

  CALL XDRS%DESTROY()

END PROGRAM
