PROGRAM PUT_VECTOR_INT8_T

  USE XDR
  USE ASSERT
  USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT8_T, C_SIZE_T
  IMPLICIT NONE

  TYPE(XDR_T) :: XDRS
  LOGICAL, DIMENSION(2) :: VALUES
  LOGICAL :: CODE

  CALL XDRS%CREATE(8)

  VALUES(1) = .FALSE.
  VALUES(2) = .TRUE.
  CODE = XDRS%PUT_VECTOR(VALUES, 2_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  VALUES = .FALSE.
  CODE = XDRS%SETPOS(1_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%GET_VECTOR(VALUES, 2_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_FALSE(VALUES(1))
  CALL ASSERT_TRUE(VALUES(2))

  CALL XDRS%DESTROY()

END PROGRAM
