PROGRAM PUT_ARRAY_UINT8_T

  USE XDR
  USE ASSERT
  USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT16_T, C_SIZE_T
  IMPLICIT NONE

  TYPE(XDR_T) :: XDRS
  INTEGER(KIND = C_INT16_T), DIMENSION(3) :: VALUES
  INTEGER(KIND = C_INT16_T), DIMENSION(:), ALLOCATABLE :: OUTPUTS
  LOGICAL :: CODE

  CALL XDRS%CREATE(16)

  VALUES(1) =   0
  VALUES(2) = 127
  VALUES(3) = 255
  CODE = XDRS%PUT_UNSIGNED_ARRAY(VALUES, 3_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%SETPOS(1_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%GET_UNSIGNED_ARRAY(OUTPUTS, 3_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_EQUALS(  0, INT(OUTPUTS(1)))
  CALL ASSERT_EQUALS(127, INT(OUTPUTS(2)))
  CALL ASSERT_EQUALS(255, INT(OUTPUTS(3)))
  DEALLOCATE(OUTPUTS)

  CALL XDRS%DESTROY()

END PROGRAM
