! DISTRIBUTION STATEMENT A. Approved for public release; distribution is
! unlimited.  Granted clearance per 88ABW-YYYY-ZZZZ.
!
! This file is declared a work of the U.S. Government and is not subject to
! copyright protection in the United States.

PROGRAM PUT_CHAR

  USE XDR
  USE ASSERT
  USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_CHAR, C_SIZE_T
  IMPLICIT NONE

  TYPE(XDR_T) :: XDRS
  CHARACTER(KIND = C_CHAR) :: VALUE
  LOGICAL :: CODE

  CALL XDRS%CREATE(12)

  CODE = XDRS%PUT_CHARACTER('a')
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%PUT_CHARACTER('b')
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%PUT_CHARACTER('c')
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%PUT_CHARACTER('c')
  CALL ASSERT_FALSE(CODE)

  CODE = XDRS%SETPOS(1_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%GET_CHARACTER(VALUE)
  CALL ASSERT_TRUE('a' == VALUE)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%GET_CHARACTER(VALUE)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_TRUE('b' == VALUE)

  CODE = XDRS%GET_CHARACTER(VALUE)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_TRUE('c' == VALUE)

  CODE = XDRS%GET_CHARACTER(VALUE)
  CALL ASSERT_FALSE(CODE)

  CALL XDRS%DESTROY()

END PROGRAM
