PROGRAM PUT_LOGICAL

  USE XDR
  USE ASSERT
  USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_SIZE_T
  IMPLICIT NONE

  TYPE(XDR_T) :: XDRS
  LOGICAL :: VALUE
  LOGICAL :: CODE

  CALL XDRS%CREATE(8)

  CODE = XDRS%PUT(.FALSE.)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%PUT(.TRUE.)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%PUT(.TRUE.)
  CALL ASSERT_FALSE(CODE)

  CODE = XDRS%SETPOS(1_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%GET(VALUE)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_FALSE(VALUE)

  CODE = XDRS%GET(VALUE)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_TRUE(VALUE)

  CODE = XDRS%GET(VALUE)
  CALL ASSERT_FALSE(CODE)

  CALL XDRS%DESTROY()

END PROGRAM
