PROGRAM PUT_VECTOR_INT8_T

  USE XDR
  USE ASSERT
  USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT8_T, C_SIZE_T
  IMPLICIT NONE

  TYPE(XDR_T) :: XDRS
  INTEGER(KIND = C_INT8_T), DIMENSION(3) :: VALUES
  LOGICAL :: CODE

  CALL XDRS%CREATE(12)

  VALUES(1) = 119
  VALUES(2) = -86
  VALUES(3) = 102
  CODE = XDRS%PUT_VECTOR(VALUES, 3_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  VALUES = 0
  CODE = XDRS%SETPOS(1_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)

  CODE = XDRS%GET_VECTOR(VALUES, 3_C_SIZE_T)
  CALL ASSERT_TRUE(CODE)
  CALL ASSERT_EQUALS(119, INT(VALUES(1)))
  CALL ASSERT_EQUALS(-86, INT(VALUES(2)))
  CALL ASSERT_EQUALS(102, INT(VALUES(3)))

  CALL XDRS%DESTROY()

END PROGRAM
